version: "3"

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile-dev
        volumes: 
            - '.:/usr/src/app/'
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
        environment:
            - TZ=UTC
        logging:
            driver: "json-file"
            options:
                max-size: "15m"
        depends_on:
            - mysql
            - es01
            - redis

    nginx:
        image: "nginx"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8001:80'

    redis:
        image: "redis"
        command: "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - '6379:6379'
        
    mysql:
        image: "mysql:cms"
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: Asia/Tehran
        volumes:
            - "../mysql:/var/lib/mysql"

    # mysql-migration:
    #     image: "mysql:cms"
    #     # ports: 
    #     #     - "3307:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_DATABASE: "${DB_DATABASE}"
    #         MYSQL_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #         TZ: Asia/Tehran
    #     volumes:
    #         - "../mysql-migration:/var/lib/mysql"

    es01:
        image: elasticsearch:7.17.0
        environment:
            - "discovery.type=single-node"
            - ELASTIC_PASSWORD=7GseHVwV6
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../elastcisearch-data:/usr/share/elasticsearch/data
        # ports:
        #     - 9200:9200

    kibana:
        image: kibana:7.17.0
        environment:
            ELASTICSEARCH_HOSTS: http://es01:9200
            ELASTICSEARCH_USERNAME: "${ELATIC_USERNAME}"
            ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
        ports:
            - 5601:5601
        depends_on:
            - es01